name: "Pull Requests: Validate"

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-node@v3
        with:
          node-version: 20.4.0
          cache: "npm"
      - run: npm ci --force
  tests:
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tests:
          - format
          - types
    name: "Test: ${{matrix.tests}}"
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-node@v3
        with:
          node-version: 20.4.0
          cache: "npm"
      - run: npm ci --force
      - run: npm run test:${{matrix.tests}}
